model_name: cbow


train_batch_size: 24
val_batch_size: 24
shuffle: True

optimizer: Adam
learning_rate: 0.025
epochs: 20
train_steps: 
val_steps: 

checkpoint_frequency: 
model_dir: weights/cbow_MalaysiaKini_200k
