checkpoint_frequency: null
epochs: 20
learning_rate: 0.025
model_dir: weights/cbow_MalaysiaKini_200k
model_name: cbow
optimizer: Adam
shuffle: true
train_batch_size: 24
train_steps: null
val_batch_size: 24
val_steps: null
